Add support for basic command line options

diff --git a/chapecron b/chapecron
--- a/chapecron
+++ b/chapecron
@@ -3,83 +3,71 @@
 set -euo pipefail
 IFS=$'\n\t'
 
+SOURCE_DIR=$(dirname "$0")
+
+source $SOURCE_DIR/src/chapecron/utils.sh
+source $SOURCE_DIR/src/chapecron/stack.sh
+source $SOURCE_DIR/src/chapecron/middlewares.sh
+
+
+utils::check_getopt || utils::fail 1 "Enhanced getopt is required"
+
+# Options
+VERBOSE=0
+HELP=0
+
+SHORT_OPTIONS=hv
+LONG_OPTIONS=help,verbose
+
+self::usage() {
+	cat <<-USAGE
+		chapecron: look after your crons while you are away
+		Usage: $0 [-v,--verbose] [-h,--help] [--] COMMAND
+		Options:
+		  -h,--help     Print this help and exit
+		  -v,--verbose  More verbose output
+	USAGE
+}
+
+PARSED=$(getopt --options=$SHORT_OPTIONS --longoptions=$LONG_OPTIONS --name "$0" -- "$@")
+if [[ $? -ne 0 ]]
+then
+	self::fail 2 "Invalid arguments. Use $0 -h to get help"
+fi
+
+eval set -- "$PARSED"
+
+while true; do
+	case "$1" in
+		-v|--verbose)
+			VERBOSE=1
+			shift
+			;;
+		-h|--help)
+			HELP=1
+			shift
+			;;
+		--)
+			shift
+			break
+			;;
+		*)
+			echo "Programming error"
+			exit 3
+			;;
+	esac
+done
 
 COMMAND="$@"
 
+
+[[ $HELP = 1 ]] && self::usage && exit 0
+[[ $VERBOSE = 1 ]] && echo "verbose: $VERBOSE, help: $HELP, command: $COMMAND"
+
+
+
 eval_command() {
   eval $COMMAND
-}
-
-
-# Stack management
-declare -a STACK
-declare -i STACK_COUNTER=0
-
-stack::add() {
-	export STACK+=($@)
-}
-
-stack::next() {
-	local NEXT_COMMAND=${STACK[$STACK_COUNTER]}
-	export STACK_COUNTER+=1
-	$NEXT_COMMAND
-}
-
-stack::run() {
-	export STACK_COUNTER=0
-	stack::next
-}
-
-
-# Chapecron
-chapecron::mktmp() {
-	export TMP=$(mktemp -d 'chapecron.XXXXXXXXXX')
-	export OUT=$TMP/cronic.out
-	export ERR=$TMP/cronic.err
-	export TRACE=$TMP/cronic.trace
-	
-	trap "{ rm -rf $TMP; }" EXIT
-	
-	stack::next
-}
-
-chapecron::run() {
-	set +e
-	stack::next >$OUT 2>$TRACE
-	RESULT=$?
-	set -e
-	
-	PATTERN="^${PS4:0:1}\\+${PS4:1}"
-	if grep -aq "$PATTERN" $TRACE
-	then
-		! grep -av "$PATTERN" $TRACE > $ERR
-	else
-		ERR=$TRACE
-	fi
-	
-	if [ $RESULT -ne 0 -o -s "$ERR" ]
-	then
-		echo -e $(chapecron::trace $COMMAND)
-	fi
-}
-
-chapecron::trace() {
-	echo "Cronic detected failure or error output for the command:"
-	echo "$@"
-	echo
-	echo "RESULT CODE: $RESULT"
-	echo
-	echo "ERROR OUTPUT:"
-	cat "$ERR"
-	echo
-	echo "STANDARD OUTPUT:"
-	cat "$OUT"
-	if [ $TRACE != $ERR ]
-	then
-		echo
-		echo "TRACE-ERROR OUTPUT:"
-		cat "$TRACE"
-	fi
 }
 
 
