Add support for plugins

diff --git a/chapecron b/chapecron
--- a/chapecron
+++ b/chapecron
@@ -4,6 +4,8 @@
 : ${CHAPECRON_DEBUG:=0}
 : ${CHAPECRON_PATH_PREFIX:=}
 
+: ${CHAPECRON_BASH_VERSION:=${BASH_VERSINFO[0]}}
+
 
 # Unofficial Bash strict mode
 set -euo pipefail
@@ -11,26 +13,26 @@ set -euo pipefail
 IFS=$'\n\t'
 
 
-#
-# Exit statuses
-# (Exit code should be narrowed to the range 64-113 to match
-# C/C++ standards and not clash with reserved ones)
-#
-ERROR_MISSING_DEPENDENCY=65
-ERROR_INVALID_ARGUMENTS=66
-ERROR_UNLOADABLE_CONFIG=70
+##
+## Global variables
+##
 
+## Exit statuses
+# Exit code should be narrowed to the range 64-113 to match C/C++ standards
+# and not clash with reserved ones
+declare -r ERROR_MISSING_DEPENDENCY=65
+declare -r ERROR_INVALID_ARGUMENTS=66
+declare -r ERROR_UNLOADABLE_CONFIG=70
+declare -r ERROR_UNLOADABLE_PLUGIN=71
+declare -r ERROR_UNKNOWN_PLUGIN=72
 
-#
-# Command line arguments
-#
-
+## Command line arguments
+declare COMMAND=''
+# Default options
+declare CONFIG_FILE=''
 # Default flags
 declare -i VERBOSE=0
 declare -i HELP=0
-
-# Default options
-declare CONFIG_FILE=''
 
 
 #
@@ -69,25 +71,26 @@ utils::fail() {
 # Array functions
 #
 array::search() {
-	local needle=$1
-	local value
-
+	local needle=$1 value
 	shift
-	for value in $(echo $@ | tr " " "\\n"); do
+	
+	eval set -- $@
+	for value in $@; do
 		[ "$value" == "$needle" ] && return 0
 	done
 	return 1
 }
 
 array::merge() {
-	local merged=()
-	local v
-
-	for v in $(echo $@ | tr " " "\\n"); do
-		if ( ! array::search $v ${merged[@]} ); then
-			merged+=("$v")
+	local merged=() value
+	
+	eval set -- $@
+	for value in $@; do
+		if ( ! array::search $value ${merged[@]} ); then
+			merged+=("$value")
 		fi
 	done
+	
   echo "${merged[@]}"
 }
 
@@ -108,8 +111,88 @@ dependencies::getopt() {
 }
 
 dependencies::bash4() {
-	[ ${BASH_VERSINFO[0]} -lt 4 ] && return 1
+	[ $CHAPECRON_BASH_VERSION -lt 4 ] && return 1
 	return 0
+}
+
+dependencies::all() {
+	dependencies::getopt || \
+		utils::fail $ERROR_MISSING_DEPENDENCY \
+								"Missing dependency: enhanced getopt"
+		            
+	dependencies::bash4  || \
+		utils::fail $ERROR_MISSING_DEPENDENCY \
+								"Missing dependency: bash 4.0+"
+}
+
+
+#
+# Command line options
+#
+options::usage() {
+	cat <<-USAGE
+		chapecron: look after your crons while you are away
+		Usage: $0 [-v,--verbose] [-h,--help] -- COMMAND
+		Options:
+		  -c,--config   Specify a configuration file (See below)
+		  -h,--help     Print this help and exit
+		  -v,--verbose  More verbose output.
+		                You can specify this option more than once
+		
+		By default, chapecron will look for configuration files at:
+		
+		- /etc/chapecron/chapecron.conf
+		- XDG_CONFIG_HOME/chapecron/chapecron.conf
+		  (usually ~/.config/chapecron/chapecron.conf)
+		
+		When specifying a configuration file as a command line option,
+		only this file will be considered.
+	USAGE
+}
+
+options::get() {
+	local parsed
+	
+	parsed=$(getopt --options=hvc: \
+									--longoptions=help,verbose,config: \
+									--name "$0" \
+									-- "$@")
+	eval set -- "$parsed"
+
+	while :; do
+		case "$1" in
+			-c|--config)
+				CONFIG_FILE=$2
+				shift 2
+				;;
+			-v|--verbose)
+				VERBOSE+=1
+				shift
+				;;
+			-h|--help)
+				HELP=1
+				shift
+				;;
+			--)
+				shift
+				break
+				;;
+			*)
+				utils::fail $ERROR_INVALID_ARGUMENTS \
+										"Unsupported option $1. Use $0 -h to get help"
+				;;
+		esac
+	done
+
+	COMMAND=$(echo "$*"	| tr "\\n" " ")
+
+	[ $HELP -eq 1 ] && options::usage && exit 0
+	
+	[ -z "$COMMAND" ] && \
+		utils::fail $ERROR_INVALID_ARGUMENTS \
+								"No command to look after. Use $0 -h to get help"
+	
+	eval "$(printf 'chapecron::command() { %s; return $?; }' $COMMAND)"
 }
 
 
@@ -117,73 +200,125 @@ dependencies::bash4() {
 # Configuration
 #
 declare -A CONFIG
+
 declare -a CONFIG_MERGEABLE
 
 CONFIG_MERGEABLE+=('plugins')
 
-# `$(eval echo "~$(whoami)")` seems to be an overly complicated way
-# to get $HOME but Sharness mess with $HOME
-CONFIG_HOME_USR=$(   ([ -z ${XDG_CONFIG_HOME+x} ] || [ -z "$XDG_CONFIG_HOME" ]) \
-									&& echo "$(eval echo "~$(whoami)")/.config" \
-									|| echo "$XDG_CONFIG_HOME" \
-								)
+config::dir() {
+	local path
+	
+	case "$1" in
+		sys)
+			path="/etc"
+			;;
+		user)
+			# `$(eval echo "~$(whoami)")` seems to be an overly complicated way
+			# to get $HOME but Sharness mess with $HOME
+			path=$(   ([ -z ${XDG_CONFIG_HOME+x} ] || [ -z "$XDG_CONFIG_HOME" ]) \
+							&& echo "$(eval echo "~$(whoami)")/.config" \
+							|| echo "$XDG_CONFIG_HOME" \
+						)
+			;;
+	esac
+	
+	echo "${path%/}/chapecron/"
+	return 0
+}
 
-CONFIG_DIR_SYS=/etc/chapecron/
-CONFIG_DIR_USR=${CONFIG_HOME_USR%/}/chapecron/
+declare -r CONFIG_DIR_SYS=$(config::dir 'sys')
+declare -r CONFIG_DIR_USR=$(config::dir 'user')
 
 config::defaults() {
 	CONFIG=( ["plugins"]="" )
 }
 
 config::loadfile() {
-	local _file=$1
-	local _tmp
+	local to_load=$1 tmp_conf name value
 
-	[ -e "$_file" ] || \
+	[ -e "$to_load" ] || \
 		utils::fail $ERROR_UNLOADABLE_CONFIG \
-								"Configuration file $_file does not exist"
+								"Configuration file $to_load does not exist"
 
-	[ -r "$_file" ] || \
+	[ -r "$to_load" ] || \
 		utils::fail $ERROR_UNLOADABLE_CONFIG \
-								"Configuration file $_file can not be read"
+								"Configuration file $to_load can not be read"
 
-	utils::info "Loading configuration from file $_file"
+	utils::info "Loading configuration from file $to_load"
 
 
-	_tmp=$(mktemp 'chapecron-config.XXXXXXXXXX')
-	utils::debug "Temporary configuration file created as $_tmp"
+	tmp_conf=$(mktemp 'chapecron-config.XXXXXXXXXX')
+	utils::debug "Temporary configuration file created as $tmp_conf"
 	if [ $CHAPECRON_DEBUG -eq 0 ]; then
-		trap "{ rm \"$_tmp\"; }" EXIT
+		trap "{ rm \"$tmp_conf\"; }" EXIT
 		utils::debug "Temporary configuration file set to be deleted after execution"
 	fi
 
-	grep -vE '^$' "$_file" | grep -vE '^#' > "$_tmp"
+	grep -vE '^$' "$to_load" | grep -vE '^#' > "$tmp_conf"
 	while IFS="=" read -r name value || [ -n "$name" ]; do
 		if (array::search "$name" "${CONFIG_MERGEABLE[@]}"); then
-			CONFIG["$name"]=$(array::merge "${CONFIG["$name"]}" "$value")
+			CONFIG["$name"]="$(array::merge "${CONFIG["$name"]}" "$value")"
 		else
 			CONFIG["$name"]="$value"
 		fi
-	done < "$_tmp"
+	done < "$tmp_conf"
 }
 
 config::load() {
+
+	config::defaults
+		
 	if [ -n "$CONFIG_FILE" ]; then
 		config::loadfile "$CONFIG_FILE"
 		return
 	fi
 
-	local _config_files=(
+	local f
+	local -a config_files
+	
+	config_files=(
 		"${CHAPECRON_PATH_PREFIX%/}${CONFIG_DIR_SYS%/}/chapecron.conf"
 		"${CHAPECRON_PATH_PREFIX%/}${CONFIG_DIR_USR%/}/chapecron.conf"
 	)
 
-	for f in "${_config_files[@]}"; do
+	for f in "${config_files[@]}"; do
 		utils::debug "Looking for a configuration file at $f"
 		if [ -e "$f" ]; then
-			utils::info "Configuration file found: $f"
 			config::loadfile "$f"
 		fi
+	done
+}
+
+
+#
+# Plugins
+#
+declare -a PLUGINS_AVAILABLE
+declare -r PLUGINS_DIR="$(dirname $(realpath $0))/plugins.d"
+
+
+plugins::load() {
+	local plugin f functions
+	
+	functions=$(declare -F | cut -d ' ' -f3)
+	
+	for plugin in "$PLUGINS_DIR"/*.sh; do
+		[ -e "$plugin" ] || \
+			utils::fail $ERROR_UNLOADABLE_PLUGIN \
+									"Plugin $plugin does not exist"
+		
+		[ -r "$plugin" ] || \
+			utils::fail $ERROR_UNLOADABLE_PLUGIN \
+									"Plugin $plugin can not be read"
+	
+		utils::debug "Loading plugin from $plugin"
+	  source "$plugin"
+	done
+	
+	for f in $(declare -F | cut -d ' ' -f3); do
+	  if ( ! array::search "$f" $functions); then
+	    PLUGINS_AVAILABLE+=("$f")
+	  fi
 	done
 }
 
@@ -199,9 +334,9 @@ stack::add() {
 }
 
 stack::next() {
-	local NEXT_COMMAND=${STACK[$STACK_COUNTER]}
+	local next=${STACK[$STACK_COUNTER]}
 	STACK_COUNTER+=1
-	$NEXT_COMMAND
+	$next
 }
 
 stack::run() {
@@ -210,11 +345,68 @@ stack::run() {
 	return $?
 }
 
+stack::build() {
+	local plugins plugin
+	
+	stack::add "chapecron::mktmp"
+	stack::add "chapecron::capture"
+	
+	if [ -n "${CONFIG['plugins']}" ]; then
+		for plugin in $(echo "${CONFIG['plugins']}" | tr " " "\\n"); do
+			if ( ! array::search "$plugin" "${PLUGINS_AVAILABLE[@]}"); then
+				utils::fail $ERROR_UNKNOWN_PLUGIN "Unknown plugin: $plugin"
+			fi
+			
+			stack::add "$plugin"
+		done
+	fi
+	
+	stack::add "chapecron::command"
+}
+
 
 #
 # Output
 #
-output::trace() {
+report::options() {
+	utils::info  "Command to be monitored: $COMMAND"
+	utils::debug "-- Command line options detected --"
+	utils::debug "config file = ${CONFIG_FILE:-undefined}"
+	utils::debug "verbose = $VERBOSE"
+	utils::debug "-- Command line options ends --"
+}
+
+report::config() {
+	local key
+	
+	utils::debug "-- Configuration loaded --"
+	for key in "${!CONFIG[@]}"; do
+		utils::debug "$key = ${CONFIG[$key]}"
+	done
+	utils::debug "-- Configuration ends --"
+}
+
+report::plugins() {
+	local plugin
+	
+	utils::debug "-- Plugins available --"
+	for plugin in "${PLUGINS_AVAILABLE[@]}"; do
+		utils::debug "$plugin"
+	done
+	utils::debug "-- Plugins ends --"
+}
+
+report::stack() {
+	local middleware
+	
+	utils::debug "-- Stack build --"
+	for middleware in "${STACK[@]}"; do
+		utils::debug "$middleware"
+	done
+	utils::debug "-- Stack ends --"
+}
+
+report::trace() {
 	echo "Cronic detected failure or error output for the command:"
 	echo "$@"
 	echo
@@ -236,17 +428,15 @@ output::trace() {
 # Chapecron own middlewares
 #
 chapecron::mktmp() {
-	local TMP
-	local OUT
-	local ERR
-	local TRACE
+	declare -g TMP
+	declare -g OUT
+	declare -g ERR
+	declare -g TRACE
 
 	TMP=$(mktemp -d 'chapecron.XXXXXXXXXX')
 	OUT=$TMP/cronic.out
 	ERR=$TMP/cronic.err
 	TRACE=$TMP/cronic.trace
-
-	export OUT ERR TRACE
 
 	utils::debug "Output files created in $TMP"
 	if [ $CHAPECRON_DEBUG -eq 0 ]; then
@@ -258,7 +448,7 @@ chapecron::mktmp() {
 	return $?
 }
 
-chapecron::run() {
+chapecron::capture() {
 	set +e
 	stack::next >"$OUT" 2>"$TRACE"
 	RESULT=$?
@@ -272,7 +462,7 @@ chapecron::run() {
 	fi
 
 	if ([ $RESULT -ne 0 ] || [ -s "$ERR" ]); then
-		echo -e "$(output::trace "$COMMAND")"
+		echo -e "$(report::trace "$COMMAND")"
 	fi
 
 	return $RESULT
@@ -282,107 +472,13 @@ chapecron::run() {
 #
 # Here we go!
 #
-dependencies::getopt || \
-	utils::fail $ERROR_MISSING_DEPENDENCY \
-							"Missing dependency: enhanced getopt"
-              
-dependencies::bash4  || \
-	utils::fail $ERROR_MISSING_DEPENDENCY \
-							"Missing dependency: bash 4.0+"
+dependencies::all
 
-# Options
-SHORT_OPTIONS=hvc:
-LONG_OPTIONS=help,verbose,config:
-
-self::usage() {
-	cat <<-USAGE
-		chapecron: look after your crons while you are away
-		Usage: $0 [-v,--verbose] [-h,--help] -- COMMAND
-		Options:
-		  -c,--config   Specify a configuration file (See below)
-		  -h,--help     Print this help and exit
-		  -v,--verbose  More verbose output.
-		                You can specify this option more than once
-		
-		By default, chapecron will look for configuration files at:
-		
-		- /etc/chapecron/chapecron.conf
-		- XDG_CONFIG_HOME/chapecron/chapecron.conf
-		  (usually ~/.config/chapecron/chapecron.conf)
-		
-		When specifying a configuration file as a command line option,
-		only this file will be considered.
-	USAGE
-}
-
-PARSED=$(getopt --options=$SHORT_OPTIONS \
-								--longoptions=$LONG_OPTIONS \
-								--name "$0" \
-								-- "$@")
-eval set -- "$PARSED"
-while :; do
-	case "$1" in
-		-c|--config)
-			CONFIG_FILE=$2
-			shift 2
-			;;
-		-v|--verbose)
-			VERBOSE+=1
-			shift
-			;;
-		-h|--help)
-			HELP=1
-			shift
-			;;
-		--)
-			shift
-			break
-			;;
-		*)
-			utils::fail $ERROR_INVALID_ARGUMENTS \
-									"Unsupported option $1. Use $0 -h to get help"
-			;;
-	esac
-done
-
-COMMAND="$*"
-
-
-[ $HELP -eq 1 ] && self::usage && exit 0
-
-
-[ -z "$COMMAND" ] && \
-	utils::fail $ERROR_INVALID_ARGUMENTS \
-							"No command to look after. Use $0 -h to get help"
-
-
-utils::info  "Command to be monitored: $COMMAND"
-
-utils::debug "Command line options detected:"
-utils::debug "config file: ${CONFIG_FILE:-undefined}"
-utils::debug "verbose: $VERBOSE"
-
-config::defaults
-config::load
-
-utils::debug "-- Configuration loaded --"
-for key in "${!CONFIG[@]}"; do
-	utils::debug "$key = ${CONFIG[$key]}"
-done
-utils::debug "-- Configuration ends --"
-
-
-eval_command() {
-	eval "$COMMAND"
-	return $?
-}
-
-# Build the middleware stack and run it
-stack::add chapecron::mktmp
-stack::add chapecron::run
-stack::add eval_command
+options::get $@ 	&& report::options
+config::load			&& report::config
+plugins::load			&& report::plugins
+stack::build			&& report::stack
 
 stack::run
-
 exit $?
 
